{
 "title": "PoC",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center; font-size: 55px\">Worker 0</p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center; font-size: 55px\">Worker 1</p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 16, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center; font-size: 55px\">Worker 2</p>"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",node=\"worker0\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",node=\"worker1\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",node=\"worker2\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{node=\"worker0\"}"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_containers{container_state=\"running\",node=\"worker0\"}"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{node=\"worker1\"}"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_containers{container_state=\"running\",node=\"worker1\"}"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{node=\"worker2\"}"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_containers{container_state=\"running\",node=\"worker2\"}"
    }
   ]
  },
  {
   "title": "Historical containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_containers{container_state=\"running\",node=\"worker0\"}",
     "legendFormat": "Containers running"
    }
   ]
  },
  {
   "title": "Historical containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_containers{container_state=\"running\",node=\"worker1\"}",
     "legendFormat": "Containers running"
    }
   ]
  },
  {
   "title": "Historical containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_containers{container_state=\"running\",node=\"worker2\"}",
     "legendFormat": "Containers running"
    }
   ]
  }
 ]
}
{
 "title": "DLR Output",
 "time": { "from": "2020-01-01T05:23:50.158Z", "to": "2020-01-01T07:39:31.414Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DLR output",
   "type": "graph",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "yaxes": [
    { "format": "kelvin" }
   ],
   "targets": [
    {
     "alias": "Surface temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dlr",
     "select": [
      [
       { "params": [ "surface_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scada ",
   "type": "graph",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scada",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}