apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress

