apiVersion: v2
type: application
name: nidhogg
description: A chart that deploys argo-cd and the Yggdrasil chart.
version: v0.4.4

dependencies:
  - name: nidhogg
    version: "v1.0.2-rc-5"
    repository: "https://distributed-technologies.github.io/helm-repository/"
