nidhogg: 
  cloud: false
  yggdrasil:
    # If this URL does not end with ".git" the template will assume that it's from a chart repo
    # If this URL does end with ".git" the template will assume that it's from a git repo
    repoURL: "https://github.com/distributed-technologies/yggdrasil.git"
    targetRevision: "main"
    # Set the ingress domain you would like to use for your ingress services
    ingressDomain: cluster.local
    clusterNetworking: 
      ipRangeStart: 172.16.0.0
      # ipRangeStop is both the ipRangeStop but also the ingress loadBalancerIP
      ipRangeStop: 172.16.0.9
    registry: harbor.sc.garagen/yggdrasil

  installCNI: true

  CNI:
    kube:
      image: 
        repository: harbor.sc.garagen/yggdrasil/weaveworks/weave-kube
    npc:
      image:
        repository: harbor.sc.garagen/yggdrasil/weaveworks/weave-npc

  argo-cd: 
    global:
      image:
        repository: harbor.sc.garagen/yggdrasil/argoproj/argocd
    controller: 
      replicas: 3
      env:
        - name: "ARGOCD_CONTROLLER_REPLICAS"
          value: "3"
      enableStatefulSet: true
    redis-ha: 
      enabled: true
      image:
        repository: harbor.sc.garagen/yggdrasil/redis
      haproxy:
        image: 
          repository: harbor.sc.garagen/yggdrasil/haproxy
      exporter:
        image: harbor.sc.garagen/yggdrasil/oliver006/redis_exporter
    redis:
      enabled: false
      dex:
      image: 
        repository: harbor.sc.garagen/yggdrasil/dexidp/dex
    server:   
      replicas: 3
      config:
        repositories: |
          - type: helm
            url: https://argoproj.github.io/argo-helm
            name: argoproj
          - type: helm
            url: https://distributed-technologies.github.io/helm-repository/
            name: dt-helmrepo
          - type: helm
            url: https://kubernetes.github.io/kube-state-metrics
            name: metrics
          - type: helm
            url: https://prometheus-community.github.io/helm-charts
            name: node-exporter
          - type: helm
            url: https://grafana.github.io/helm-charts
            name: grafana
          - type: helm
            url: https://strimzi.io/charts/
            name: strimzi-kafka-operator
          - type: helm
            url: https://confluentinc.github.io/cp-helm-charts/
            name: cp-helm-charts
          - type: helm
            url: https://charts.rook.io/release
            name: rook-release
        resource.customizations: |
          admissionregistration.k8s.io/MutatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/clientConfig/caBundle
          admissionregistration.k8s.io/ValidatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/clientConfig/caBundle
              - /webhooks/0/namespaceSelector/matchExpressions/2
          networking.k8s.io/Ingress:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs
      service: 
        type: NodePort

    configs:
      secret:
        # This is not a secret password. It is okay to be on github
        argocdServerAdminPassword: $2y$12$m4KC7G9d8NFxInl7GRpQ1OpPPrF43Msa33ZQjj0YmT6f8uwjHW8AO
        argocdServerAdminPasswordMtime: "2021-01-02T15:04:05Z"


  rookCeph: 
    repoURL: https://github.com/distributed-technologies/services-rook.git
    targetRevision: 0.1.2
    path: "chart"

  rookCephCluster: 
    repoURL: https://github.com/distributed-technologies/services-ceph.git
    targetRevision: 0.1.4
    path: "chart"

  rookCephHelper: 
    repoURL: https://github.com/distributed-technologies/services-rook-helper.git
    targetRevision: "main"
    path: "chart"

  ntp: 
    repoURL: https://github.com/distributed-technologies/services-ntp.git
    targetRevision: "v0.1.0"
    path: "chart"
    image: 
      tag: main
